### ISSUE TITLE
How to support it.only('...')

### ISSUE THREAD

**Issue by daKmoR** [LarsDenBakker/web-test-runner#35]
Consider these 2 test files

```js
// b.test.js
describe('test b', () => {
  it('undefined is a function', () => {
    expect(undefined).to.be.undefined;
  });

  it('true equals true', () => {
    expect(true).to.equal(false);
  });
});

// c.test.js
describe('test c', () => {
  it.only('true equals true', () => {
    expect(true).to.equal(true);
  });
});
```

## Expected
1 test get's executed
(I put the only there)

## Actual
3 tests get executed

## Thoughts?
As all tests run in parallel it also means that `.only` can only influence the current file?

What would be the workflow to only execute specific tests (when multiple files are involved)?

**Comment by LarsDenBakker** [comment]
This is a downside of running tests in parallel. I wonder if we really need this though, we only report about failed tests and we only rerun test files that have a dependency on the changed file. So in the end you don't get a lot of spam.

It would be nice to support this though, one thought I had was that when you click a debug link in the terminal it would focus on that test file only and not report anything else.

**Comment by daKmoR** [comment]
actually that is the first thing I usually do when I start with something 😅 
e.g. I wanted to look into how these tests are executed so I thought I will just use one test (via setting .only) and then see which files are executed...
but yeah way more was executed then I thought 😅

What we could do is a "simple filter" on files (e.g. like how browser "prescreen" the html text for certain keywords like preload before it actually starts processing the html)

e.g. if a any test file has `.only(` somewhere then we should filter out all files which do not have a `.only`... this will probably cover 90% of the use cases - however cases where tests get generated by imported functions will not work - that would be way tougher as we would need to follow imports, ...

I think looping once over all the files and doing an `indexOf('.only')` should not be too big of a performance impact...

if that sounds good I can work on it 👍

**Comment by LarsDenBakker** [comment]
I don't think doing a regexp or scanning a string is a good idea for this, it would be too magical and create unexpected results.

This isn't easy to implement right now, because we just start a browser and load the tests. For this we would need to separately crawl all the test files. And it needs to be able to work for frameworks other than mocha, and non-standard JS if/when people implement this.

You can execute single test files by not using a glob, but just pointing to a single test file. I'd like to see if that and a debug link would be sufficient.

Another approach when running the tests we see the .only from mocha itself, and ping that back to the test runner to "focus" on this.

**Comment by LarsDenBakker** [comment]
My idea was also when you run the test runner with the `--debug` flag, it shows a page with links to select the test file you want to debug. This because we can't just open a lot of tabs when you are debugging in the browser. That would also serve this use case I think.

**Comment by daKmoR** [comment]
What I would like is a "simple" (one click, a few characters in one file) way to run a single test or a single describe...

if we get this with a `--debug` flag and a click in the CI that sounds good to me as well 👍

**Comment by LarsDenBakker** [comment]
The debug mode would only allow you to select which test file to run, it doesn't know anything about individual tests until the test framework and tests are loaded. It would be both that and a `.only`.

I get what you want, I'm just saying that it's not possible with test isolation unless you scan all test files upfront. You'd need to scan the test files as well as it's dependencies if you want to be completely correct. And you need to rescan it each time you change the file.

I checked and Jest has the same limitation. Their advice is to run an individual test file using the command line (`wtr test/foo.test.js`)

**Comment by daKmoR** [comment]
hmmm back in the days (before UIs) we had "nice" text "wizards"... I am wondering if it could help here...

maybe something like this

```
=== Test run 1 (10:10:21) ===

[1] demo/test/b.test.js
  test b > undefined is a function
    AssertionError: expected undefined to be a function
        at Context.<anonymous> (demo/test/b.test.js:5:29)

[2] demo/test/c.test.js
  test b > undefined is a function
    AssertionError: expected undefined to be a function
        at Context.<anonymous> (demo/test/c.test.js:5:29)
```

so if you hit 1 on your keyboard then it will run tests only for `demo/test/b.test.js`

🤔

**Comment by LarsDenBakker** [comment]
I was thinking to do this on file level, but I think we could make this work on a per test level like that 🤔

**Comment by LarsDenBakker** [comment]
This was implemented
