### ISSUE TITLE
Streaming terminal on Github Actions

### ISSUE THREAD

**Issue by jorenbroekema** [LarsDenBakker/web-test-runner#57]
I'm using the test runner also in Github Actions to automate things, and I was looking at the console output https://github.com/code-workshop-kit/cwk-frontend/runs/736671657?check_suite_focus=true 

It seems like the streaming feature isn't working and some of the diagnostics output gets duplicated on top of each other.

Not sure about whether this is something you can fix in WTR or whether it's a shortcoming of the console/terminal output of Github Actions

**Comment by LarsDenBakker** [comment]
This was fixed.
